stages:
  - test
  - deploy

variables:
  HEROKU_APP_NAME: "hostfamily-be"

rake-test:
  stage: test
  image: ruby:2.4.1
  script:
    - apt-get update -qy
    - bundle install --path /cache
    - bundle exec rake db:environment:set RAILS_ENV=test
    - bundle exec rake db:migrate
    - bundle exec rake db:test:prepare
    - bundle exec rspec


production:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --strategy=git --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    # Execute migration after deployment
    - "curl -n -X POST https://api.heroku.com/apps/${HEROKU_APP_NAME}/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rake db:migrate\""
  environment:
    name: production
    url: https://${HEROKU_APP_NAME}.herokuapp.com/
  only:
    - production

staging:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --strategy=git --app=${HEROKU_APP_NAME}-staging --api-key=$HEROKU_API_KEY
    # Execute migration after deployment
    - "curl -n -X POST https://api.heroku.com/apps/${HEROKU_APP_NAME}-staging/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rake db:migrate\""
  environment:
    name: staging
    url: https://${HEROKU_APP_NAME}-staging.herokuapp.com/
  only:
    - production
    - staging
